namespace NodeJS {
  interface ProcessEnv {
    BASE_URL: string
    NEXT_PUBLIC_API_URL: string
    NEXT_PUBLIC_HOSTNAME: string
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: string
    NEXT_PUBLIC_FB_APP_ID: string
    NEXT_PUBLIC_VK_APP_ID: string
    NEXT_PUBLIC_RECAPTCHA_CLIENT_KEY: string
    NEXT_PUBLIC_RECAPTCHA_SERVER_KEY: string
    NEXT_PUBLIC_FINGERPRINT_KEY: string
    NEXT_PUBLIC_SUBSCTIPTION_ENDING_DAY_COUNT: string
    NEXT_PUBLIC_TOKEN_REFRESH_INTERVAL_HOURS: string
    NEXT_PUBLIC_UPGRADE_CHANNELS_LOGO_PROTO: string
    NEXT_PUBLIC_LAODER_TIMEOUT: string
  }
}
